enum ActionTypes {
  FETCH_STAFF_BY_ID = 'FETCH_STAFF_BY_ID',
  FETCH_STAFF = 'FETCH_STAFF',
  CREATE_STAFF = 'CREATE_STAFF',
  CREATE_STAFF_USER = 'CREATE_STAFF_USER',
  UPDATE_STAFF = 'UPDATE_STAFF',
  DELETE_STAFF = 'DELETE_STAFF',
}

export default ActionTypes;
