enum MutationTypes {
  CHANGE_MENU_OPEN = 'CHANGE_MENU_OPEN',
  CHANGE_CURRENT_STEP = 'CHANGE_CURRENT_STEP',
  CHANGE_SELECTED_COMPANY = 'CHANGE_SELECTED_COMPANY',
  CHANGE_SELECTED_SERVICE = 'CHANGE_SELECTED_SERVICE',
  CHANGE_SELECTED_STAFF = 'CHANGE_SELECTED_STAFF',
  CHANGE_SELECTED_DATETIME = 'CHANGE_SELECTED_DATETIME',
  CHANGE_SELECTED_CUSTOMER = 'CHANGE_SELECTED_CUSTOMER',
  CHANGE_SELECTED_NOTICE = 'CHANGE_SELECTED_NOTICE',
  ADD_RESERVED_APPOINTMENTS = 'ADD_RESERVED_APPOINTMENTS',
}

export default MutationTypes;
