enum MutationTypes {
  CHANGE_MENU_OPEN = 'CHANGE_MENU_OPEN',
  CHANGE_CURRENT_STEP = 'CHANGE_CURRENT_STEP',
  CHANGE_SELECTED_COMPANY = 'CHANGE_SELECTED_COMPANY',
  CHANGE_SELECTED_SERVICE = 'CHANGE_SELECTED_SERVICE',
  CHANGE_SELECTED_STAFF = 'CHANGE_SELECTED_STAFF',
  CHANGE_SELECTED_DATETIME = 'CHANGE_SELECTED_DATETIME',
  CHANGE_SELECTED_CUSTOMER = 'CHANGE_SELECTED_CUSTOMER',
  CHANGE_SELECTED_NOTICE = 'CHANGE_SELECTED_NOTICE',
  ADD_RESERVED_APPOINTMENTS = 'ADD_RESERVED_APPOINTMENTS',
  CHANGE_OPEN_SERVICE_CREATE_MODAL = 'CHANGE_OPEN_SERVICE_CREATE_MODAL',
  CHANGE_OPEN_CALENDAR_MODAL = 'CHANGE_OPEN_CALENDAR_MODAL',
  CHANGE_OPEN_SERVICE_EDIT_MODAL = 'CHANGE_OPEN_SERVICE_EDIT_MODAL',
  CHANGE_OPEN_STAFF_CREATE_MODAL = 'CHANGE_OPEN_STAFF_CREATE_MODAL',
  CHANGE_OPEN_STAFF_EDIT_MODAL = 'CHANGE_OPEN_STAFF_EDIT_MODAL',
  CHANGE_SELECTED_WORKER = 'CHANGE_SELECTED_WORKER',
  CHANGE_RESERVED_APPOINTMENTS = 'CHANGE_RESERVED_APPOINTMENTS',
  REMOVE_RESERVED_APPOINTMENT_BY_ID = 'REMOVE_RESERVED_APPOINTMENT_BY_ID',
  CHANGE_TOUR = 'CHANGE_TOUR',
}

export default MutationTypes;
