enum ActionTypes {
  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  FETCH_CUSTOMERS = 'FETCH_CUSTOMERS',
  FETCH_CUSTOMERS_BY_NAME = 'FETCH_CUSTOMERS_BY_NAME',
  UPDATE_CUSTOMER = 'UPDATE_CUSTOMER',
}

export default ActionTypes;
