enum ActionTypes {
  FETCH_SERVICE = 'FETCH_SERVICE',
  FETCH_SERVICES = 'FETCH_SERVICES',
  CREATE_SERVICE = 'CREATE_SERVICE',
  UPDATE_SERVICE = 'UPDATE_SERVICE',
  DELETE_SERVICE = 'DELETE_SERVICE',
}

export default ActionTypes;
