enum MutationTypes {
  CHANGE_SERVICES = 'CHANGE_SERVICES',
  ADD_SERVICE = 'ADD_SERVICE',
  UPDATE_SERVICE_BY_ID = 'UPDATE_SERVICE_BY_ID',
  REMOVE_SERVICE_BY_ID = 'REMOVE_SERVICE_BY_ID',
}

export default MutationTypes;
