enum ActionTypes {
  FETCH_APPOINTMENT = 'FETCH_APPOINTMENT',
  FETCH_APPOINTMENT_BY_CUSTOMER = 'FETCH_APPOINTMENT_BY_CUSTOMER',
  CREATE_APPOINTMENT = 'CREATE_APPOINTMENT',
  UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT',
  CANCEL_APPOINTMENT = 'CANCEL_APPOINTMENT',
}

export default ActionTypes;
