enum ActionTypes {
  FETCH_COMPANY = 'FETCH_COMPANY',
  FETCH_STATS = 'FETCH_STATS',
  FETCH_BARCODE = 'FETCH_BARCODE',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  UPLOAD_IMAGE = 'UPLOAD_IMAGE',
  DELETE_IMAGE = 'DELETE_IMAGE',
  SEND_CONTACT = 'SEND_CONTACT',
}

export default ActionTypes;
