enum ActionTypes {
  FETCH_COMPANY = 'FETCH_COMPANY',
  FETCH_STATS = 'FETCH_STATS',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  UPLOAD_IMAGE = 'UPLOAD_IMAGE',
  DELETE_IMAGE = 'DELETE_IMAGE',
}

export default ActionTypes;
